name: Update Project Board

on:
  pull_request:
    types: [opened, closed]
  issues:
    types: [opened, closed]

jobs:
  update_board:
    runs-on: ubuntu-latest
    steps:
    - name: Move PR to In Progress
      if: github.event_name == 'pull_request' && github.event.action == 'opened'
      run: # Your script to move PR to "In Progress" column
    - name: Move Closed PR to Done
      if: github.event_name == 'pull_request' && github.event.action == 'closed'
      run: # Your script to move closed PR to "Done" column
